name: Deploy

on:
  push:
    branches: ["main"]

concurrency:
  group: "deploy"
  cancel-in-progress: true

jobs:
  build:
    name: "Deploy"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "ap-southeast-2"

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialise terraform state
        working-directory: terraform/upload
        run: terraform init

      - name: Apply terraform state
        working-directory: terraform/upload
        run: terraform apply -auto-approve
